[MHES]
Abbreviation=MHES
Description=Matthew Henry — Español (Spanish)
DataPath=./modules/comments/zcom/mhes/
ModDrv=zCom
SourceType=OSIS
Encoding=UTF-8
CompressType=ZIP
BlockType=BOOK
Versification=KJV
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISHeadings
GlobalOptionFilter=OSISScripref
Lang=es
Category=Commentaries
LCSH=Commentary.Spanish
About=Comentario devocional seleccionado del Comentario de Matthew Henry y traducido al español.
Version=0.1.1
SwordVersionDate=2026-08-06
DistributionLicense=Public Domain
MinimumVersion=1.5.9
InstallSize=5026562
