[MHJA]
Abbreviation=MHJA
Description=Matthew Henry — 日本語 (Japanese)
DataPath=./modules/comments/zcom/mhja/
ModDrv=zCom
SourceType=OSIS
Encoding=UTF-8
CompressType=ZIP
BlockType=BOOK
Versification=KJV
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISHeadings
GlobalOptionFilter=OSISScripref
Lang=ja
Category=Commentaries
LCSH=Commentary.Japanese
About=マタイ・ヘンリー註解書から選び抜き、日本語に訳した敬虔な註解書。
Version=0.1.1
SwordVersionDate=2026-08-06
DistributionLicense=Public Domain
MinimumVersion=1.5.9
InstallSize=2215364
