[MHKO]
Abbreviation=MHKO
Description=Matthew Henry — 한국어 (Korean)
DataPath=./modules/comments/zcom/mhko/
ModDrv=zCom
SourceType=OSIS
Encoding=UTF-8
CompressType=ZIP
BlockType=BOOK
Versification=KJV
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISHeadings
GlobalOptionFilter=OSISScripref
Lang=ko
Category=Commentaries
LCSH=Commentary.Korean
About=매튜 헨리 주석에서 가려 뽑아 한국어로 옮긴 경건 주석.
Version=0.1.7
SwordVersionDate=2026-07-17
DistributionLicense=Public Domain
MinimumVersion=1.5.9
InstallSize=4522551
