[MHM]
Abbreviation=MHM
Description=Matthew Henry — Modern English
DataPath=./modules/comments/zcom/mhm/
ModDrv=zCom
SourceType=OSIS
Encoding=UTF-8
CompressType=ZIP
BlockType=BOOK
Versification=KJV
GlobalOptionFilter=OSISFootnotes
GlobalOptionFilter=OSISHeadings
GlobalOptionFilter=OSISScripref
Lang=en
Category=Commentaries
LCSH=Commentary.English
About=A modern-English devotional commentary derived from Matthew Henry's Commentary.
Version=0.1.9
SwordVersionDate=2026-07-20
DistributionLicense=Public Domain
MinimumVersion=1.5.9
InstallSize=4750481
